services:
    nginx:
        image: anismk/nginx-server
        container_name: anismk-nginx-server
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ${NGINX_ROOT_FOLDER}/logs:/logs
            - ${NGINX_ROOT_FOLDER}/srv:/srv
            - ${NGINX_ROOT_FOLDER}/tls:/tls
            - ${NGINX_ROOT_FOLDER}/config/nginx:/etc/nginx
        restart: unless-stopped
        depends_on:
            - php
        networks:
            - nginx-network
        extra_hosts:
            - "docker.host.ip:172.17.0.1"
    php:
        image: anismk/php-fpm
        volumes:
            - ${NGINX_ROOT_FOLDER}/srv:/var/www/html
            - ${NGINX_ROOT_FOLDER}/config/php:/php-fpm
        networks:
            - nginx-network
        restart: unless-stopped

networks:
    nginx-network:
        driver: bridge